 import turtle 
 t = turtle . turtle ()
t . speed (5) 

t . fillcolor ("red") 
t .begin _ fill ()
for i in range (2) 
t . forward (300) 
t  rught (90) 
t . forward (100) 
t . right (90)
t. end _ finall () 
t.penup ()
t.goto (0,- 100)
t .pendown () fillcolor ("white") 
t. i in range (2) 
t .forward (100) 
t. right (90) 
t . end _ fill () 
t . end _ done ()